# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Health Lab
email: health@meedan.com
description: >- # this means to ignore newlines until "baseurl:"
  Meedan’s Digital Health Lab is an applied research initiative to improve public health through digital innovation, participatory research, and equity-centered design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
#   - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Server Config options
livereload: true    # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port


# Get data from Contentful Develop Environment
contentful:
  output: true
  spaces:
    - landingPages: 
        space: ENV_CONTENTFUL_DHL_SPACE_ID
        access_token: ENV_CONTENTFUL_DHL_ACCESS_TOKEN
        cda_query:
          content_type: 'landingPage'
        client_options:
          api_url: preview.contentful.com
        all_entries: true
        destination: 'contentful/spaces/'
    - sections: 
        space: ENV_CONTENTFUL_DHL_SPACE_ID
        access_token: ENV_CONTENTFUL_DHL_ACCESS_TOKEN
        cda_query:
          content_type: 'section'
        client_options:
          api_url: preview.contentful.com
        all_entries: true
        destination: 'contentful/spaces/'
    - publications: 
        space: ENV_CONTENTFUL_DHL_SPACE_ID
        access_token: ENV_CONTENTFUL_DHL_ACCESS_TOKEN
        cda_query:
          content_type: 'modulePublication'
        client_options:
          api_url: preview.contentful.com
        all_entries: true
        destination: 'contentful/spaces/'
    - cards: 
        space: ENV_CONTENTFUL_DHL_SPACE_ID
        access_token: ENV_CONTENTFUL_DHL_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleCard'
        client_options:
          api_url: preview.contentful.com
        all_entries: true
        destination: 'contentful/spaces/'
    - moduleListItems: 
        space: ENV_CONTENTFUL_DHL_SPACE_ID
        access_token: ENV_CONTENTFUL_DHL_ACCESS_TOKEN
        cda_query:
          content_type: 'moduleListItem'
        client_options:
          api_url: preview.contentful.com
        all_entries: true
        destination: 'contentful/spaces/'


# Generate pages from Contentful data files
page_gen-dirs: true
page_gen:
  - data: 'contentful.spaces.landingPages.landingPage'
    template: 'landing'
    name: 'url'
    dir: 'pages'